CREATE TABLE lineitem (
  l_orderkey      INTEGER NOT NULL,
  l_partkey       INTEGER NOT NULL,
  l_suppkey       INTEGER NOT NULL,
  l_linenumber    INTEGER NOT NULL,
  l_quantity      FLOAT NOT NULL,
  l_extendedprice FLOAT NOT NULL,
  l_discount      FLOAT NOT NULL,
  l_tax           FLOAT NOT NULL,
  l_returnflag    CHAR(1) NOT NULL,
  l_linestatus    CHAR(1) NOT NULL,
  l_shipdate      DATE NOT NULL,
  l_commitdate    DATE NOT NULL,
  l_receiptdate   DATE NOT NULL,
  l_shipinstruct  CHAR(25) NOT NULL,
  l_shipmode      CHAR(10) NOT NULL,
  l_comment       VARCHAR(44) NOT NULL,
  PRIMARY KEY     (l_orderkey, l_linenumber),
  INDEX l_ok      (l_orderkey ASC),
  INDEX l_pk      (l_partkey ASC),
  INDEX l_sk      (l_suppkey ASC),
  INDEX l_sd      (l_shipdate ASC),
  INDEX l_cd      (l_commitdate ASC),
  INDEX l_rd      (l_receiptdate ASC),
  INDEX l_pk_sk   (l_partkey ASC, l_suppkey ASC),
  INDEX l_sk_pk   (l_suppkey ASC, l_partkey ASC)
)
